#!/usr/bin/python -tt

import re

def main():
  module = AnsibleModule(
    argument_spec = dict(
      name=dict(aliases=['pkg']),
    ),
  )
  pkg = module.params['name']
  rc,out,err = module.run_command('pear install "%s"' % pkg)
  if rc == 0:
      module.exit_json(rc=rc, out=out, err=err, changed=True, failed=False)
  if err == '' and rc == 1:
    p = re.compile('.*is already installed and is the same as the released version.*')
    if p.match(out):
      module.exit_json(out=out, err=err, failed=False, changed=False)
    module.fail_json(rc=rc, out=out, msg=err, failed=True)

  module.fail_json( rc=rc, out=out, err=err )

# this is magic, see lib/ansible/module_common.py
#<<INCLUDE_ANSIBLE_MODULE_COMMON>>
main()

